name: React App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: install
      run: npm install
    - name: build
      run: npm run build

    # get commit hash id
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
      with:
        prefix: "commit-"

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_ID }}/front-meservation:${{ steps.commit.outputs.short }} .

    - name: Docker image latest tagging
      run: docker tag ${{ secrets.DOCKERHUB_ID }}/front-meservation:${{ steps.commit.outputs.short }} ${{ secrets.DOCKERHUB_ID }}/front-meservation:latest
      
    - name: Docker-hub login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker-hub push w/ commit tag
      run: docker push ${{ secrets.DOCKERHUB_ID }}/front-meservation:${{ steps.commit.outputs.short }}

    - name: Docker-hub push w/ latest tag
      run: docker push ${{ secrets.DOCKERHUB_ID }}/front-meservation:latest
      
    - name: SSH remote command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: ${{ secrets.EC2_PORT }}
        script: |          
          sudo docker stop front-meservation
          sudo docker rm front-meservation
          sudo docker pull ${{ secrets.DOCKERHUB_ID }}/front-meservation:${{ steps.commit.outputs.short }}
          sudo docker run \
            -e "REACT_APP_MESERVATION_URL=${{ secrets.REACT_APP_MESERVATION_URL }}" \
            --name front-meservation -p 80:80 -d ${{ secrets.DOCKERHUB_ID }}/front-meservation:${{ steps.commit.outputs.short }}

    
